version: "3.8"

services:
  app-client:
    container_name: k8s-app-client-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    networks:
      - k8s-app-network
    restart: always

networks:
  # network apenas para client e server
  k8s-app-network:
    name: k8s-app-network
    # default network type.
    driver: bridge
